import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession } from 'next-auth'
import Logout from './Logout'
import Link from 'next/link'

import Provider from "@/app/context/clientProvider"
import { options } from "@/app/api/auth/[...nextauth]/options"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(options)

  return (
    <html lang="en">
      <body className={inter.className}>
        { !!session && <Logout /> }
        { !session && <Link href="/api/auth/signin">Login</Link> }
        <Provider session={session}>
          {children}
        </Provider>
      </body>
    </html>
  )
}
